### ISSUE TITLE
PE agents should upgrade to the masters PE version by default. 

### ISSUE THREAD

**Issue by brettswift** [puppetlabs/puppetlabs-puppet_agent#109]
This is an opinion I guess, but wanted to suggest it here. 

I am testing the unreleased 1.2.0 code (hash e7eee94d5c76b3132309e65cb41a45b2bd49c99b) and as per the docs (which are correct)  you need to explicitly supply a puppet version. 

It'd be nice if there was a custom function in this module that grabbed that version off the puppet master itself..  and used it at compile time.   This would be one less thing to remember to upgrade when upgrading your puppet master.    It would still allow for agents to have a more controlled process.

If desired it could be a feature toggle that we could just set once. 

This may not be a common use case, but in ours - we spin up net new Puppet masters and then migrate VM's to the new master when we want to upgrade them.   It keeps the upgrade path a bit cleaner and our current way of controlling the upgrade.  (Was helpful in the 3.x --> 2015.x  upgrade). 

Thoughts?

**Comment by brettswift** [comment]
Specific versions do work on new masters, but when I apply this stuff to the old master it fails.  Quite obviously because the new package doesn't exist in that puppet infrastructure.

Scenario: 

feature/test_upgrade   --> develop on the control repo.  (roles/profiles). 

Feature is tested on 2016.1.1,  with package_version set to 1.4.1.(in a common to all linux.pp profile)    works.. and upgrades agents there. 

I test for backwards compatibility expecting it to fail, and of course it does because package version 1.4.1 doesn't exist.

The pe_repo class doesn't seem to have what I need, or maybe I can't find what I'm looking for in it?  It seems like this module is the plan moving forward?  I'm a bit disappointed this kind of stuff isn't baked right into the enterprise product.

**Comment by MikaelSmith** [comment]
We've talked about having a special `package_version` value with the meaning that the agent should ensure it's set to the latest version supported by the master it's connected to, but haven't implemented it.

ping @highb @jpartlow on that, and putting this in the core enterprise product.

**Comment by brettswift** [comment]
I found a workaround today actually and forgot to update this. There's a
function in the puppet_enterprise module that I found that gets the aio
version from the compile master. As its a function that's one way of
getting a value from the master into the catalog - which works for us.

Pretty simple workaround really. Maybe params.pp could use that function if
it's available.

**Comment by MikaelSmith** [comment]
It does actually, at https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/params.pp#L81. However, we only use it when upgrading from PE 3.8.

**Comment by brettswift** [comment]
Ah!

I didn't catch that when I was poking around.

Well thanks. This module might have made our upgrade process a little
simpler. For big upgrades in the future - as I mentioned - having puppet
manage it by itself would be nice.

Our current 3-4 upgrade was a bit sledge hammer like as we did a complete
uninstall and reinstall.

The pe_repo and pc_repo differences do get a bit confusing. If you install
via the curl script you get a pe_repo entry but if it's been upgraded here
you get the pc_repo.

Anyways thanks for this module. It made the upgrade to 2016 seamless.

**Comment by MikaelSmith** [comment]
There was an issue about pe_repo vs pc_repo (https://github.com/puppetlabs/puppetlabs-puppet_agent/issues/105) that I've turned into a modules ticket [MODULES-3250](https://tickets.puppetlabs.com/browse/MODULES-3250).

**Comment by dannygoulder** [comment]
looking forward to

> a special `package_version `value with the meaning that the agent should ensure it's set to the latest version supported by the master it's connected to

**Comment by geoffnichols** [comment]
Thank you for opening this issue. We're working on migrating all of this project's Github issues into our JIRA tracker. 

For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-3250.
