### ISSUE TITLE
 Syntax error

### ISSUE THREAD

**Issue by grajeshwaran** [puppetlabs/puppetlabs-puppet_agent#118]
The issue "Unknown function: 'pe_compiling_server_aio_build' is fixed, but now we get the following error - Error 400 on SERVER: Syntax error at ','; expected ')' at  modules/puppet_agent/manifests/init.pp:66 

This is on Centos 6.5.

**Comment by MikaelSmith** [comment]
Which version are you using? I'm not sure what code that line refers to.

When I've seen that error before, it's been when I wasn't using `parser=future`.

**Comment by grajeshwaran** [comment]
parser=future fixed that syntax error. Further when working with version specific installation, I came across another error, before posting it here I googled and found there was one more link about the same issue - 
https://gist.github.com/glarizza/e92a5e4ddd67b707f7b1

**Comment by MikaelSmith** [comment]
You may also be running into stringified facts. Have you checked everything in https://forge.puppet.com/puppetlabs/puppet_agent#setup-requirements?
