### ISSUE TITLE
Attempting 3.8.7 agent upgrade to puppet-agent 1.5.0 certdir variable error

### ISSUE THREAD

**Issue by sepulworld** [puppetlabs/puppetlabs-puppet_agent#123]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: The value 'certdir' cannot be converted to Numeric. at /etc/puppetlabs/code/environments/development/modules/puppet_agent/manifests/prepare/ssl.pp:27:27

Applying via:

class {'::puppet_agent':
  package_version => '1.5.0',
}

Ubuntu 14.04

**Comment by sepulworld** [comment]
Ubuntu 14.04

**Comment by MikaelSmith** [comment]
Looks like you have `stringified_facts` set to `true`, so it fails to index into a structured fact.

**Comment by sepulworld** [comment]
Ah! I missed that.  Thank you @MikaelSmith
