### ISSUE TITLE
Windows language

### ISSUE THREAD

**Issue by ManiacTwister** [puppetlabs/puppetlabs-puppet_agent#133]
Hello,

I have found a "bug" while uprading windows servers to version 4. The problem is that install_puppet.bat searchs for an english string in the tasklist output. On Windows machines with an different language pack enabled this doesn't work. For example in german the output is "Es werden keine Aufgaben mit den angegebenen Kriterien ausgeführt". 

I suggest to either fix this the following way: http://stackoverflow.com/a/15449358
Or at least add this to the known issue list in the readme

**Comment by aharden** [comment]
We found the same issue on Japanese servers.  We're now running off a patched version of the module.  I put our workaround here: https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/134.

**Comment by MikaelSmith** [comment]
Should be fixed in https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/135 (which will be in the next Forge release).
