### ISSUE TITLE
module is incompatible with strict_variables

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-puppet_agent#141]
module fails to compile if strict_variables is set to true

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: '_package_version'. at /etc/puppetlabs/code/environments/production/modules/puppet_agent/manifests/init.pp:108:8

**Comment by MikaelSmith** [comment]
https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/1.2.0/manifests/init.pp#L108 presumably. That makes sense, should be an easy fix.

**Comment by MikaelSmith** [comment]
Ok, maybe not simple. We rely on a number of facts that may or may not be defined.

**Comment by MikaelSmith** [comment]
Filed as https://tickets.puppetlabs.com/browse/MODULES-3710.

**Comment by MikaelSmith** [comment]
I started trying to do something at https://github.com/MikaelSmith/puppetlabs-puppet_agent/tree/MODULES-3710, but haven't made progress recently.

**Comment by geoffnichols** [comment]
Thank you for opening this issue. We're working on migrating all of this project's Github issues into our JIRA tracker. For updates on this issue, please follow  https://tickets.puppetlabs.com/browse/MODULES-3710.
