### ISSUE TITLE
Upgrading Windows from 3.8.7

### ISSUE THREAD

**Issue by dandunckelman** [puppetlabs/puppetlabs-puppet_agent#142]
I'm working to migrate our Foreman/Puppet environment from v3.x to v4.x.  I've stood up a new Foreman on the latest Foreman/Puppet.

I was able to upgrade one of our Windows 2012R2 servers from Puppet v3.7.3 to the latest (v4.5.3 ATM) using this module, but I came across these issues initially (found in the puppetserver.log on the Foreman/Puppet server):

```
2016-08-10 21:23:06,256 WARN  [qtp753368735-65] [puppetserver] Puppet Unknown variable: '::common_appdata'. at /etc/puppetlabs/code/environments/update_to_puppet_4/modules/puppet_agent/manifests/params.pp:54:50
2016-08-10 21:23:06,277 WARN  [qtp753368735-65] [puppetserver] Puppet Unknown variable: '::platform_tag'. at /etc/puppetlabs/code/environments/update_to_puppet_4/modules/puppet_agent/manifests/params.pp:75:17
2016-08-10 21:23:06,282 WARN  [qtp753368735-65] [puppetserver] Puppet Unknown variable: 'mco_install'. at /etc/puppetlabs/code/environments/update_to_puppet_4/modules/puppet_agent/manifests/params.pp:97:21
2016-08-10 21:23:06,284 WARN  [qtp753368735-65] [puppetserver] Puppet Unknown variable: 'logdir'. at /etc/puppetlabs/code/environments/update_to_puppet_4/modules/puppet_agent/manifests/params.pp:99:21
2016-08-10 21:23:06,326 WARN  [qtp753368735-65] [puppetserver] Puppet Unknown variable: '::puppet_agent::params::_source'. at /etc/puppetlabs/code/environments/update_to_puppet_4/modules/puppet_agent/manifests/init.pp:36:22
2016-08-10 21:23:06,346 INFO  [qtp753368735-65] [puppetserver] Scope(Class[Puppet_agent]) puppet_agent performs no actions if the master's agent version cannot be determed on PE 3.x
2016-08-10 21:23:06,423 INFO  [qtp753368735-65] [puppetserver] Puppet Compiled catalog for foremanproxy-02.ta.local in environment update_to_puppet_4 in 0.91 seconds
```

So, I looked at those and worked to solve them w/ this process:
- Updated from puppet 3.7.3 to 3.8.7 to get it to the latest 3.x version (per the Puppet docs)
  - Downloaded `https://downloads.puppetlabs.com/windows/puppet-3.8.7-x64.msi` from https://downloads.puppetlabs.com/windows/
- Create a facts file to get the **puppet_agent** module to work
  - Added a facts file in `c:\ProgramData\PuppetLabs\facter\facts.d\tmp-facts.yaml` with this content:

            common_appdata: "c:/programdata"
            platform_tag: "derp" # cuz I have no idea what this should be
            mco_install: "c:/programdata/puppetlabs/mcollective" # I didn't install mcollective
            logdir: "c/tmp"
- Modified `/etc/puppetlabs/code/environments/update_to_puppet_4/modules/puppet_agent/manifests/params.pp`:

        -  $_is_pe = ($::is_pe or is_function_available('pe_compiling_server_version'))
        +  $_is_pe = false
  - I tried setting the **is_pe** fact to be **false**, but because the condition above is an **or**, that 2nd condition seems to return true
      - Maybe there's an issue w/ that `is_function_available()` check?
- Then I was able to run `puppet agent -t` and puppet was upgraded to 4.5.3

        notice	/Stage[main]/Puppet_agent::Windows::Install/File[C:\Users\dan\AppData\Local\Temp\1\install_puppet.bat]/ensure	defined content as '{md5}21b6e1ce64a5bf2db70e817826779bef'
        notice	/Stage[main]/Puppet_agent::Prepare::Puppet_config/Ini_setting[main/pluginsync]/ensure	removed
        notice	/Stage[main]/Puppet_agent::Windows::Install/Exec[install_puppet.bat]/returns	executed successfully
        notice	/Stage[main]/Puppet_agent::Windows::Install/Exec[fix inheritable SYSTEM perms]/returns	executed successfully

Please help me make this less hands on (as I thought it would be).

**Comment by MikaelSmith** [comment]
You appear to be running with strict_variables enabled, also reported at https://github.com/puppetlabs/puppetlabs-puppet_agent/issues/141. Fixing that should help.

I'm not sure what might be going on with `is_function_available` (part of puppetlabs/stdlib); do you have any modules from a PE install left-over somewhere?

**Comment by dandunckelman** [comment]
On my puppetmaster, it has `strict_variables = false`

If it was enabled, it would have caused a compilation error when it found the **Unknown variable**.  Since `strict_variables = false`, it just warns.

I don't think I have any PE-related modules (we've never used PE).
- To further test that, I created this `test.pp` (I wanted to use `assert_type()` but that's only available when the future parser is enabled):

        $pe = $::is_pe
        notice("IS PE: ${pe}")

        $func_avail = is_function_available('pe_compiling_server_version')
        notice("FUNC AVAILABLE: $func_avail")

        $combined_check = ($pe or $func_avail)
        notice("COMBINED: ${combined_check}")

        $double_false_check = (false or false)
        notice("DOUBLE FALSE CHECK: ${double_false_check}")
- Then I applied it on another Windows 2012 VM that I haven't upgraded yet:

        PS C:\Users\Administrator\Downloads> puppet apply .\test.pp
        Notice: Scope(Class[main]): IS PE: false
        Notice: Scope(Class[main]): FUNC AVAILABLE: false
        Notice: Scope(Class[main]): COMBINED: true
        Notice: Scope(Class[main]): DOUBLE FALSE CHECK: false
        Notice: Compiled catalog for foreman-proxy-01.ta.local in environment production in 0.05 seconds
        Notice: Finished catalog run in 0.09 seconds
        PS C:\Users\Administrator\Downloads> puppet --version
        3.7.3
- This got me thinking...so I amended the script to this:

        $pe = $::is_pe
        notice("IS PE: ${pe}")
        validate_bool($pe)

        $func_avail = is_function_available('pe_compiling_server_version')
        notice("FUNC AVAILABLE: $func_avail")
        validate_bool($func_avail)

        $combined_check = ($pe or $func_avail)
        notice("COMBINED: ${combined_check}")
        validate_bool($combined_check)

        $double_false_check = (false or false)
        notice("DOUBLE FALSE CHECK: ${double_false_check}")
        validate_bool($double_false_check)
- Which resulted in this:

        PS C:\Users\Administrator\Downloads> puppet apply .\test.pp
        Notice: Scope(Class[main]): IS PE: false
        Error: "false" is not a boolean.  It looks to be a String at C:/Users/Administrator/Downloads/test.pp:3 on node foreman-proxy-01.ta.local
        Error: "false" is not a boolean.  It looks to be a String at C:/Users/Administrator/Downloads/test.pp:3 on node foreman-proxy-01.ta.local
  - So, when the **::is_pe** var is **undef** it's not a boolean...I think this was updated in newer Puppet versions...but that would be why this failed (AFAIK).
      - Then again, I don't understand why things didn't work when I explicitly set the **is_pe** fact to **false** in the aforementioned facts file

Here's my `Puppetfile`:

```
forge 'forge.puppetlabs.com'

mod 'puppetlabs/apache', '1.10.0' # portal_web dependency
mod 'puppetlabs/apt', '2.2.2' # apache, nodejs dependency
mod 'puppet/archive', '1.0.0' # Rundeck dependency
mod 'alexkappa/aws', '0.0.1' # Dependency of a specific Rundeck job
mod 'chocolatey/chocolatey', '1.2.6' # windows package management
mod 'puppetlabs/concat', '2.2.0' # apache dependency
mod 'pltraining/dirtree', '0.2.2' # rundeck dependency
mod 'garethr/docker', '5.3.0' # gitlab runner dependency
mod 'puppet/download_file', '1.3.0' # download files on windows
mod 'vshn/gitlab', '1.9.1' # gitlab/gitlab runner install/configuration
mod 'golja/gnupg', '1.2.3' # rvm dependency
mod 'puppetlabs/haproxy', '1.5.0' # load balancer
mod 'puppetlabs/inifile', '1.5.0' # rundeck dependency
mod 'puppetlabs/java', '1.6.0' # manage installations of java
mod 'puppetlabs/java_ks', '1.4.1' # Manage arbitrary Java keystore files
mod 'yo61/logrotate', '1.4.0' # logrotate rule management
mod 'puppetlabs/mysql', '3.8.0' # database used by portal
#mod 'fsalum/newrelic' # install/configure newrelic server
mod 'puppet-newrelic', # install/configure newrelic server
  :branch => 'specify_windows_provider',
  :git    => 'https://github.com/dandunckelman/puppet-newrelic'
mod 'newrelic/newrelic_plugins', # helper to install the NewRelic plugin installer and plugins
  :branch => 'fix_class_inheritance',
  :git    => 'https://github.com/dandunckelman/newrelic_plugins_puppet'
mod 'puppet/nodejs', '2.0.1' # js-server used by portal/builder
mod 'example42/perl', # vmwaresdk dependency
  :git => 'https://github.com/example42/puppet-perl.git',
  :ref => 'd790ba90f8b526ae61fe6ae6efbdd869de2ca3d1'
mod 'puppetlabs/powershell', '2.0.2' # powershell exec provider
mod 'puppetlabs/puppet_agent', '1.2.0' # update puppet client from 3.x to 4.x
mod 'example42/puppi', '2.2.1' # perl dependency
mod 'stankevich/python', '1.14.0' # aws dependency
mod 'zack/r10k', '3.2.0' # deployment tool for managing puppet modules/hiera data across environments
mod 'puppetlabs/registry', '1.1.3' # module used to manage the registry, dependency of wsus_client
mod 'puppet/rundeck', '3.1.0' # job orchestrator tool
mod 'maestrodev/rvm', '1.13.1' # ruby version installation/management
mod 'nanliu/staging', '1.0.3' # mysql dependency
mod 'puppetlabs/stdlib', '4.12.0' # apache, apt, concat, mysql, nodejs, rundeck dependency
mod 'puppetlabs/transition', '0.1.0' # dependency of puppet_agent
mod 'puppetlabs/vcsrepo', '1.3.2' # portal_web/boxbuilder dependency
mod 'example42/vsftpd', '2.0.15' # ftp server
mod 'basti1302/wait_for', # rundeck dependency; ability to wait for certain conditions to be met
  :git => 'https://github.com/basti1302/puppet-wait-for.git',
  :ref => '7da9594cece8ae4f9d3c9c76e898de9a679a87af'
mod 'puppetlabs/wsus_client', '1.0.2' # Manage WSUS settings for clients
mod 'badgerious/windows_env', '2.2.2' # Manage Windows environment variables
```

**Comment by dandunckelman** [comment]
Might be related to this:  https://docs.puppet.com/puppet/4.5/reference/lang_updating_manifests.html#boolean-facts-are-always-real-booleans

**Comment by dandunckelman** [comment]
Looks like that's the case.

When I modified the client's `puppet.conf` to add `stringify_facts=false` it passed the boolean validation.

**Comment by MikaelSmith** [comment]
Oh, that's a requirement to use the module in general. I'm surprised you were able to hack it to work at all. See https://forge.puppet.com/puppetlabs/puppet_agent#setup-requirements.

**Comment by dandunckelman** [comment]
I'm just that good :wink: 

Haha, but seriously...I should've read that.

Thanks
