### ISSUE TITLE
Permissions on puppet-agent-x64.msi attempt to update every Puppet run

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-puppet_agent#146]
After using the module to upgrade from 3.8.2 to PE 2016.2.1 am seeing the Windows agents get updated every Puppet run in the PE 2016.2.1 environment (as far as I can tell, the upgrade was successful):

mode changed '0664' to '0644'
Source:	/Stage[main]/Puppet_agent::Prepare::Package/File[C:\ProgramData\Puppetlabs\packages\puppet-agent-x64.msi]/mode
File:	/etc/puppetlabs/code/environments/myenv/modules/puppet_agent/manifests/prepare/package.pp Line: 40

Looking at the file itself, it has:
Everyone: Read
SYSTEM: Full control
Administrators: Special
 -> Administrators have all permissions except for "Full control" and "Traverse folder / execute file"

I tried removing the 6 checkboxes for write permissions by hand on my test node.  Puppet then responded that the permissions needed to change from 0444 to 0644.  Apparently when it did that change, it did not do so successfully, for it then started back with the need to change the file from 0664 to 0644.

Per this ticket: https://tickets.puppetlabs.com/browse/PUP-5491
The reason for this behavior is because when puppet service runs as SYSTEM, the default DACL (analogous to umask) will cause any newly created file/dir to have owner Administrators (note plural) and group SYSTEM. [...] By comparison, when running in an elevated context (Administrator), then the owner will be you, and group will be None.

However, from the behavior I'm seeing, I almost wonder if the owner of the file is Administrators -and- the group is Administrators as well, in which case those values need to be set to the same thing (e.g. 0664 or 0444, but not 0644)?  Or should Puppet be updating the Windows file permissions differently?

From that same ticket I linked:
"I found a reference in Mechanics of User Identification and Authentication that explains this. SYSTEM is an implicit / hidden member of the Administrators group [...] an explicit grant to Administrators should also cover SYSTEM in theory as well."

FYI, I do get the same permissions change every run when running "puppet agent -t" versus running puppet as the service.

**Comment by MikaelSmith** [comment]
Fix merged, and filed https://tickets.puppetlabs.com/browse/MODULES-3834 to track further.
