### ISSUE TITLE
Errors with RHEL4 install

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-puppet_agent#155]
When attempting to install on RHEL4:

Error: Failed to apply catalog: Parameter ensure failed on Package[puppet-agent]: Provider up2date must have features 'versionable' to set 'ensure' to '1.5.3-1.el4' at /etc/puppetlabs/code/environments/release26/modules/puppet_agent/manifests/install.pp:110

Per the docs, up2date does not have feature 'versionable', and there doesn't appear to be a way to change the package provider from up2date to yum with the current module.

We're working around it by setting the package version to undef instead of a specific version for RHEL4 only, which manages the upgrade from 3->4 but will not work when we upgrade 4->4.  However, we have so few RHEL4 left that we can decide at that point whether to upgrade by hand or to extend the module with a PR if it hasn't been done yet.

I mostly wanted to report the issue since the module says that it supports RHEL4.

**Comment by MikaelSmith** [comment]
Thanks for reporting this!

**Comment by MikaelSmith** [comment]
Created https://tickets.puppetlabs.com/browse/MODULES-3895 to track work this.

**Comment by geoffnichols** [comment]
Thank you for opening this issue. We're migrating all of this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-3895.
