### ISSUE TITLE
Warning: Unknown variable

### ISSUE THREAD

**Issue by sts** [puppetlabs/puppetlabs-puppet_agent#156]
When using the module it prints out the following two warnings:

**Warning: Unknown variable: '::platform_tag'. at /root/puppet/modules/puppet_agent/manifests/params.pp:75:17**
**Warning: Unknown variable: '_package_version'. at /root/puppet/modules/puppet_agent/manifests/init.pp:108:8**

```platform_tag``` seems to be a fact coming from puppet enterprise, which isn't included in normal puppet. I'm using the module in a masterless setup.

```
# puppet --version
4.6.2
# puppet config print strict_variables
false
```

**Comment by MikaelSmith** [comment]
There's a chance this is a bug exclusive to Puppet 4.6.x. I'll take a look.

**Comment by MikaelSmith** [comment]
Created https://tickets.puppetlabs.com/browse/MODULES-3896 for tracking the fix.

**Comment by sts** [comment]
Thanks @MikaelSmith, I just tested your branch, this fixes the issue.
