### ISSUE TITLE
puppet.conf logdir?

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-puppet_agent#157]
Should the module update the logdir setting in puppet.conf to reflect the new log paths?

All the agents still have it as:
logdir = /var/log/pe-puppet

but it looks like logs now go under /var/log/puppetlabs/puppet?

**Comment by MikaelSmith** [comment]
That wasn't critical to getting a working environment, so we left it alone. However, the module could probably be updated to detect whether you had the default PE setting and update it to the new location.

**Comment by esalberg** [comment]
Not a big issue - I can update that using our base profile as well.  It might be worth documenting if you don't address it at some point?

**Comment by MikaelSmith** [comment]
Definitely, I can try to note things where the default might have changed but we don't touch them.
