### ISSUE TITLE
${::servername} variable not populated by default? 

### ISSUE THREAD

**Issue by MosesMendoza** [puppetlabs/puppetlabs-puppet_agent#166]
I installed the puppetlabs-puppet_agent module on a PE agent using pmt:

```
[root@rhel7 ~]# puppet module install --target-dir /root/modules puppetlabs-puppet_agent
Notice: Preparing to install into /root/modules ...
Notice: Created target directory /root/modules
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/root/modules
└─┬ puppetlabs-puppet_agent (v1.2.0)
  ├── puppetlabs-apt (v2.3.0)
  ├── puppetlabs-inifile (v1.6.0)
  ├── puppetlabs-stdlib (v4.12.0)
  └── puppetlabs-transition (v0.1.0)
```

And tried to use it via puppet apply, with the following failure:

```
[root@rhel7 ~]# puppet apply --modulepath /root/modules -e " class { '::puppet_agent': package_version => '1.7.0', is_pe => true } "
Warning: Unknown variable: '::servername'. at /root/modules/puppet_agent/manifests/params.pp:19:29
Notice: Compiled catalog for rhel7.localdomain in environment production in 0.51 seconds
Error: Parameter baseurl failed on Yumrepo[pc_repo]: Validate method failed for class baseurl: the scheme https does not accept registry part: :8140 (or bad hostname?) at /root/modules/puppet_agent/manifests/osfamily/redhat.pp:95
```

debugging in pry, the yumrepo type validate block has this value:

```
[1] pry(#<Puppet::Type::Yumrepo::Baseurl>)> value
=> "https://:8140/packages//el-7-x86_64"
```

It appears as if the `${::servername}` fact isn't populated on this host maybe? I think this fact comes from the [`server_facts`](https://docs.puppet.com/puppet/latest/reference/lang_facts_and_builtin_vars.html#serverfacts-variable) hash, which isn't available by default? 

Or I could just be doing something wrong? If I'm not, perhaps we should document that you have to set `trusted_server_facts` to `true` (which enables this fact)?

**Comment by MosesMendoza** [comment]
Filed this as https://tickets.puppetlabs.com/browse/MODULES-3946 - I can close this issue if we'd prefer to centralize commentary there

**Comment by MikaelSmith** [comment]
Tracked in the ticket.
