### ISSUE TITLE
syntax error at init.pp.68 with puppet 3.7.x

### ISSUE THREAD

**Issue by khaefeli** [puppetlabs/puppetlabs-puppet_agent#186]
Hi,

it looks like there is a syntax error in the latest 1.3.0 init.pp

`puppet parser validate manifests/init.pp`
`Error: Could not parse for environment production: Syntax error at ')'; expected '}' at /tmp/puppetlabs-puppet_agent/manifests/init.pp:68`

see: https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/init.pp#L68

looks like the regex isn't closed correctly refering to:

https://docs.puppet.com/puppet/latest/reference/function.html#split

I've no idea what was the plan for this "Strip git sha from dev builds", so I couln't create a PR.

Edit: need to clarify that I'm using the debian jessie 3.7.2 in a vagrant box and try to "puppet apply" my manifest:

> Version 1.3.0 is compatible with:
Puppet Enterprise 2016.4.x, 2016.2.x, 2016.1.x, 2015.3.x, 2015.2.x, 3.8.x, 3.7.x
Puppet >= 3.7.0 < 5.0.0

with 4.8.0 everyhting is working.

cheers,
Kevin

**Comment by highb** [comment]
Thanks for creating this bug report! I'll get a 3.7 agent up to repro and fix this.

**Comment by MikaelSmith** [comment]
Can you verify that you're using `--parser=future` (or have it set in puppet.conf)? This module expects future parser functionality.

**Comment by MikaelSmith** [comment]
I believe this is related to using future parser. If that suggestion didn't resolve the issue, please reopen it.
