### ISSUE TITLE
Add PUPPET_AGENT_STARTUP_MODE=Automatic to the msi installer

### ISSUE THREAD

**Issue by Renelast** [puppetlabs/puppetlabs-puppet_agent#197]
By adding PUPPET_AGENT_STARTUP_MODE=Automatic to the msi installer options we can ensure the services that should be started by the msi are actually started.
This is not done if the previous version of the agent was installed with PUPPET_AGENT_STARTUP_MODE=Manual or even Disabled.

**Comment by MikaelSmith** [comment]
@glennsarti thoughts on this?

**Comment by glennsarti** [comment]
You could inspect the current service state (Auto/Manual/Disabled) and install with the appropriate variable.  I also have code ready for https://tickets.puppetlabs.com/browse/MODULES-4214 which allow people at add arbitrary MSI install params which would also cover this use case

**Comment by MikaelSmith** [comment]
Created https://tickets.puppetlabs.com/browse/MODULES-4243 to track this.
