### ISSUE TITLE
Handle deprecated settings in Puppet 5.0.0 (app_management and others)

### ISSUE THREAD

**Issue by hlindberg** [puppetlabs/puppetlabs-puppet_agent#206]
When handling an upgrade to Puppet 5.0.0, there are several deprecated settings that should be removed in an upgrade.
These are:
* `app_management`
* `ignorecache`
* `configtimeout`
* `trusted_server_facts`

If kept they have no effect, but may lead to deprecation warnings (and subsequently when these settings are removed; lead to errors)

**Comment by MikaelSmith** [comment]
I think we can fix this up after the puppet_agent 1.3.2 release. I'm expecting we'll do a 2.0 release that drops support for Puppet 3 and old Ruby versions.

**Comment by joshcooper** [comment]
ping @geoffnichols

**Comment by geoffnichols** [comment]
Thank you for opening this issue. We're working on migrating all of this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4986.
