### ISSUE TITLE
SLES not supported at 

### ISSUE THREAD

**Issue by pearcec** [puppetlabs/puppetlabs-puppet_agent#213]
I tried this on a SLES box.

```
class {'::puppet_agent':
  is_pe => false,
  manage_repo => false
}
```
Got this
```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: E
rror while evaluating a Function Call, SLES not supported at /etc/puppetlabs/code/environments/production/modules/puppet
_agent/manifests/osfamily/suse.pp:7:5 on node hslesd01.hersheys.com","issue_kind":"RUNTIME_ERROR"}
```

Reading through the code not sure what is_pe has to do with it?  I am running SLES 11.3

Switch to

 ```
 if $::operatingsystem != 'SLES' {
   fail("${::operatingsystem} not supported")
 }
```

Ran and got 

`File 'repomd.xml' from repository 'Puppet Labs PC1 Repository sles 11 - x86_64' is unsigned, continue? [yes/no] (no)`

Is that why it is not supported?

**Comment by MikaelSmith** [comment]
I suspect a little work to get the GPG key in place on SLES is needed. SLES without PE isn't supported, so nothing's been done to verify it works. Improvements in that area would be welcomed.

**Comment by geoffnichols** [comment]
Thank you for opening this. We're migrating this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4990.
