### ISSUE TITLE
tr -- misaligned contruct on Redhat family

### ISSUE THREAD

**Issue by leemachine** [puppetlabs/puppetlabs-puppet_agent#214]
On Redhat family systems, the GPG keys get imported every run since the exec call is returning false.

The fix appears to be ensure upper and lower are wrapped around single quotes to prevent expansion.

```
echo "ABCDEFG" | tr [:upper:] [:lower:]
tr: misaligned [:upper:] and/or [:lower:] construct
```

```
echo "ABCDEFG" | tr '[:upper:]' '[:lower:]'
abcdefg
```

```
rpm -q gpg-pubkey-`echo $(gpg --throw-keyids < /etc/pki/rpm-gpg/RPM-GPG-KEY-puppetlabs) | cut --characters=11-18 | tr [:upper:] [:lower:] tr: misaligned [:upper:] and/or [:lower:] construct
package gpg-pubkey- is not installed
```

```
rpm -q gpg-pubkey-`echo $(gpg --throw-keyids < /etc/pki/rpm-gpg/RPM-GPG-KEY-puppetlabs) | cut --characters=11-18 | tr '[:upper:]' '[:lower:]'`
gpg-pubkey-4bd6ec30-4c37bb40
```

**Comment by MikaelSmith** [comment]
Ah thanks, I'll take a look later.

**Comment by leemachine** [comment]
Any update?

It seems to be an issue with the version of /bin/tr in the follow two coreutils versions:

coreutils-8.22-15.el7_2.1.x86_64
coreutils-8.22-18.el7_2.1.x86_64


It works as is on coreutils-8.22-18.el7_2.1.x86_64, but not coreutils-8.22-15.el7_2.1.x86_64

**Comment by MikaelSmith** [comment]
Created https://tickets.puppetlabs.com/browse/MODULES-4478, I'll have a PR up in a sec.
