### ISSUE TITLE
solaris needs to force the 'sun' provider or give the opportunity to change it

### ISSUE THREAD

**Issue by sirinek** [puppetlabs/puppetlabs-puppet_agent#219]
At our site, for Solaris 10 hosts, we set the default Package provider to 'pkgutil' because we have a local OpenCSW repo (hacked up a means of creating the indexes, etc)   However, we aren't putting the puppet agent package in there, as it is hosted by the masters, as it should be. 

Normally, the default Solaris package provider is 'sun'.   If I edit manifests/install.pp and add provider => 'sun' to $_package_options for Solaris 10, everything works fine. However, the module gives me no way to set the provider to use for the agent package resource, so it fails because puppet assumes our site default of 'pkgutil' for the package provider.

**Comment by sirinek** [comment]
Pull request:  https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/220

**Comment by MikaelSmith** [comment]
Filed as https://tickets.puppetlabs.com/browse/MODULES-4547.

**Comment by geoffnichols** [comment]
Thank you for opening this issue (and submitting the pull request).

We're working on migrating all of this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4547.
