### ISSUE TITLE
We should disable backup to filebucket for the local_package_file_path file resource

### ISSUE THREAD

**Issue by Renelast** [puppetlabs/puppetlabs-puppet_agent#225]
[This](https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/prepare/package.pp#L51) resource should have backup => false set so when an upgrade happens any old installer files do not get sent to the filebucket.

**Comment by geoffnichols** [comment]
Thank you for opening this. We're migrating this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4989.
