### ISSUE TITLE
Resource pc_repo_force is always reported as absent.

### ISSUE THREAD

**Issue by lordbink** [puppetlabs/puppetlabs-puppet_agent#228]
Resource pc_repo_force is always reported as absent. So adding the repo is done every time. It should only need to run once.

**Comment by geoffnichols** [comment]
Thank you for opening this. We're migrating this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4988.
