### ISSUE TITLE
Bump puppetlabs/apt dependency

### ISSUE THREAD

**Issue by den-is** [puppetlabs/puppetlabs-puppet_agent#230]
```
Warning: Module 'puppetlabs-apt' (v4.0.0) fails to meet some dependencies:
  'puppetlabs-puppet_agent' (v1.3.2) requires 'puppetlabs-apt' (>= 2.0.1 < 3.0.0)
```
According to the Puppet Style Guide https://docs.puppet.com/puppet/latest/style_guide.html#dependencies , epel and apt are soft dependencies and should be treated as such.

**Comment by geoffnichols** [comment]
Thank you for opening this issue. We're working on migrating all of this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4987.
