### ISSUE TITLE
Unknown function: 'pe_compiling_server_aio_build'

### ISSUE THREAD

**Issue by olevole** [puppetlabs/puppetlabs-puppet_agent#98]
puppet-agent                    1.4.1-1trusty
puppetserver                     2.3.1-1puppetlabs1
Ubuntu 14.04.4 LTS

Troubles with 1.1.0 and latest code from https://github.com/puppetlabs/puppetlabs-puppet_agent.git i've got error:
~~~
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Unknown function: 'pe_compiling_server_aio_build'. at /etc/puppetlabs/code/environments/production/modules/public/puppet_agent/manifests/params.pp:81:16 on node 
~~~

**Comment by MikaelSmith** [comment]
https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/params.pp#L81 probably needs to be guarded on the function existing. I'll look at fixing that up in a bit.

**Comment by MikaelSmith** [comment]
Are you using a PE master? It should be guarded by `is_pe`.

**Comment by olevole** [comment]
Look's like it was a one-time problem - after synchronization .rb files by client problem went away. Thank you for your response, ive close this issue.

**Comment by MikaelSmith** [comment]
Hmm, I'm curious how it got into that state. Glad it worked now though.

**Comment by olevole** [comment]
it is observed on all of my nodes when moving from puppet 3  to puppet 4: http://pastebin.com/iK2NB9gU . So, it neccessary to run 
~~~
puppet agent -t
~~~

twice for me.

**Comment by MikaelSmith** [comment]
Are you also changing the master you point to when you do the upgrade?

**Comment by olevole** [comment]
No, master was originally on 4 version. Somehow (by mistake) the clients  was  on puppet3 and this installation (puppet3 client <-> puppet4 ) worked successfully until recently.

**Comment by MikaelSmith** [comment]
Put up a PR to try and avoid that problem anyway.
